parameters:
    bukashk0zzz_liip_imagine_pre_serialization.listener.class: Bukashk0zzz\LiipImagineSerializationBundle\EventListener\JmsPreSerializeListener
    bukashk0zzz_liip_imagine_post_serialization.listener.class: Bukashk0zzz\LiipImagineSerializationBundle\EventListener\JmsPostSerializeListener

services:
    _defaults:
        public: true

    bukashk0zzz_liip_imagine.metadata.attribute_reader:
        class:  Bukashk0zzz\LiipImagineSerializationBundle\Metadata\AttributeReader
        public: false

    bukashk0zzz_liip_imagine_pre_serialization.listener:
        class: '%bukashk0zzz_liip_imagine_pre_serialization.listener.class%'
        arguments:
            - '@router.request_context'
            - '@bukashk0zzz_liip_imagine.metadata.attribute_reader'
            - '@liip_imagine.cache.manager'
            - '@vich_uploader.storage'
            - '@event_dispatcher'
        tags:
            - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize }

    bukashk0zzz_liip_imagine_post_serialization.listener:
        class: '%bukashk0zzz_liip_imagine_post_serialization.listener.class%'
        arguments:
            - '@router.request_context'
            - '@bukashk0zzz_liip_imagine.metadata.attribute_reader'
            - '@liip_imagine.cache.manager'
            - '@vich_uploader.storage'
            - '@event_dispatcher'
        tags:
            - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize }
